### ISSUE TITLE
Plan to use spec getStats?

### ISSUE THREAD

**Issue by xdumaine** [opentok/rtcstats#94] opened 2019-04-11 18:44 UTC
Do you plan to migrate to or adopt spec getStats in this lib?

**Comment by fippo** [comment] 2019-04-11 18:45
https://github.com/lifeonairteam/rtcstats-server/issues/204 -- its mostly a matter of finding time and then validating that the features are still correct.

**Comment by xdumaine** [comment] 2019-04-16 18:40
This blows up in canary (75). Seems like old getStats is gone. `Uncaught (in promise) TypeError: Failed to execute 'getStats' on 'RTCPeerConnection': parameter 2 is not of type 'MediaStreamTrack'.`

**Comment by fippo** [comment] 2019-04-16 22:21
@henbos?!

seems to blow up when using an it like this on https://webrtc.github.io/samples/src/content/peerconnection/pc1/
```
pc1.getStats(res => console.log("result!"), e => console.error("error", e.toString()))
```
bad version: 75.0.3745.4
good version: 73.0.3683.86

Arguably can be fixed by removing the error callback but...

**Comment by fippo** [comment] 2019-04-16 23:22
https://bugs.chromium.org/p/chromium/issues/detail?id=953512 -- yay, I did not have to file a chrome bug!

**Comment by henbos** [comment] 2019-04-17 07:31
This was not intentional, I'll try to fix it, see bug.

**Comment by henbos** [comment] 2019-04-17 07:31
You can be assured a deprecation warning will be used for quite some time before it is removed for realsies.

**Comment by henbos** [comment] 2019-04-17 07:34
Please migrate to new getStats though, see [this issue](https://crbug.com/webrtc/10428) for trying to get most stuff missing into the new one.

**Comment by henbos** [comment] 2019-04-17 08:25
Update: I wrote on [the bug fippo referenced](https://bugs.chromium.org/p/chromium/issues/detail?id=953512) but I'll write here too: While this is a regression that I will attempt to fix today, not that the errorCallback way of calling getStats was _never valid_. It worked only because prior to the regression it ignored the second argument, making it call equivalent to getStats(successCallback). But the type of the second argument was always "optional MediaStreamTrack? selector", so the error message you're seeing is reasonable. Before the regression we did the unreasonable thing to not tell you that you're using the wrong arguments. I'll make it less reasonable again to avoid breaking existing apps.

**Comment by fippo** [comment] 2019-04-17 11:38
This is fixed in 5.0.1 -- @xdumaine @arrrgh @dagingaa let me know if you need a backport to some of the old versions

**Comment by henbos** [comment] 2019-04-17 12:49
Update: This is now fixed in Chrome, but you'll have to wait for the next Canary cut to try it out.

**Comment by fippo** [comment] 2019-05-06 08:29
no more action here, see server bug for migration efforts.

**Closed as completed by fippo** 2019-05-06 08:29 UTC
